-- MySQL Script generated by MySQL Workbench
-- Mon 20 Jul 2026 04:08:13 PM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema weather
-- -----------------------------------------------------
DROP DATABASE IF EXISTS weather;

-- -----------------------------------------------------
-- Schema weather
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weather` ;
USE `weather` ;

-- -----------------------------------------------------
-- Table `weather`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`location` (
  `locid` INT NOT NULL COMMENT 'Location id',
  `location` VARCHAR(60) NOT NULL COMMENT 'Location name (room, patio etc)',
  `outside` INT NULL COMMENT 'Outside flag (1-location is outside, 0 or null - location is Inside) ',
  PRIMARY KEY (`locid`),
  UNIQUE INDEX `idlocation_UNIQUE` (`locid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weather`.`sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`sensor` (
  `sensorid` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `location_locid` INT NOT NULL,
  PRIMARY KEY (`sensorid`),
  UNIQUE INDEX `densorid_UNIQUE` (`sensorid` ASC) VISIBLE,
  INDEX `fk_sensor_location_idx` (`location_locid` ASC) VISIBLE,
  CONSTRAINT `fk_sensor_location`
    FOREIGN KEY (`location_locid`)
    REFERENCES `weather`.`location` (`locid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'List od sensors';


-- -----------------------------------------------------
-- Table `weather`.`metric`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`metric` (
  `metricid` INT NOT NULL,
  `metric` VARCHAR(45) NULL,
  PRIMARY KEY (`metricid`))
ENGINE = InnoDB
COMMENT = 'List of possible metrics';


-- -----------------------------------------------------
-- Table `weather`.`metering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`metering` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mdatatime` DATETIME NOT NULL,
  `value` FLOAT NOT NULL,
  `sensor_sensorid` INT NOT NULL,
  `metric_metricid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_metering_sensor1_idx` (`sensor_sensorid` ASC) VISIBLE,
  INDEX `fk_metering_metric1_idx` (`metric_metricid` ASC) VISIBLE,
  UNIQUE INDEX `metering_uq` (`metric_metricid` ASC, `sensor_sensorid` ASC, `mdatatime` ASC) VISIBLE,
  INDEX `metering_dt` (`metric_metricid` ASC, `mdatatime` ASC) VISIBLE,
  CONSTRAINT `fk_metering_sensor1`
    FOREIGN KEY (`sensor_sensorid`)
    REFERENCES `weather`.`sensor` (`sensorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_metering_metric1`
    FOREIGN KEY (`metric_metricid`)
    REFERENCES `weather`.`metric` (`metricid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Keep metering values from sensors';


-- -----------------------------------------------------
-- Table `weather`.`metering_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`metering_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mdatatime` DATETIME NOT NULL COMMENT 'Start of the hourly bucket this row summarizes',
  `value` FLOAT NOT NULL COMMENT 'Average of the raw values archived into this bucket',
  `sample_count` INT NOT NULL COMMENT 'Number of raw metering rows averaged into this bucket',
  `sensor_sensorid` INT NOT NULL,
  `metric_metricid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_metering_history_sensor1_idx` (`sensor_sensorid` ASC) VISIBLE,
  INDEX `fk_metering_history_metric1_idx` (`metric_metricid` ASC) VISIBLE,
  UNIQUE INDEX `metering_history_uq` (`metric_metricid` ASC, `sensor_sensorid` ASC, `mdatatime` ASC) VISIBLE,
  CONSTRAINT `fk_metering_history_sensor1`
    FOREIGN KEY (`sensor_sensorid`)
    REFERENCES `weather`.`sensor` (`sensorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_metering_history_metric1`
    FOREIGN KEY (`metric_metricid`)
    REFERENCES `weather`.`metric` (`metricid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Hourly-averaged archive of metering rows past the retention cutoff - see WeatherDb.archive_metering()';

-- User creation and passwords live in db/weather_users.sql (gitignored) -
-- copy db/weather_users.sql.example, fill in real passwords matching your
-- .env's DB_PASSWORD/DB_PASSWORD_READONLY, and run it after this script:
--   mysql < db/weather.sql
--   mysql < db/weather_users.sql

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `weather`.`metric`
-- -----------------------------------------------------
START TRANSACTION;
USE `weather`;
INSERT INTO `weather`.`metric` (`metricid`, `metric`) VALUES (1, 'temperature');
INSERT INTO `weather`.`metric` (`metricid`, `metric`) VALUES (2, 'humidity');
INSERT INTO `weather`.`metric` (`metricid`, `metric`) VALUES (3, 'CO2');
INSERT INTO `weather`.`metric` (`metricid`, `metric`) VALUES (4, 'TVOC');
INSERT INTO `weather`.`metric` (`metricid`, `metric`) VALUES (5, 'battery');
INSERT INTO `weather`.`metric` (`metricid`, `metric`) VALUES (6, 'pressure');
INSERT INTO `weather`.`metric` (`metricid`, `metric`) VALUES (7, 'illuminance');

COMMIT;

